on: [push]

env:
  GITHUB_ACTIONS: true

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
    steps:
    - uses: actions/checkout@v1
    - name: Install Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install python dependencies
      run: pip install pytest selenium webdriver_manager
    
    - name: Install go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.6

    - name: Install react
      run: |
        cd frontend/fizzbuzz
        npm install

    - name: Run tests
      run: |
        cd frontend/fizzbuzz
        npm run start &
        cd ../..
        pytest system-test/test_no_backend.py
        export FIZZBUZZ_SERVERPORT=8000
        export FIZZBUZZ_CLIENTURL="http://localhost:3000"
        export FIZZ="Fizz"
        export BUZZ="Buzz"
        go run main.go &
        sleep 10
        pytest system-test/test_backend.py
